apiVersion: v1
kind: Pod
metadata:
  name: nextjs-pod
  labels:
    app: nextjs-app
spec:
  containers:
    - name: nextjs-container
      image: dharrsankube/dharrsan-portfolio-amd:v1.1
      ports:
        - containerPort: 3000
